### ISSUE TITLE
Owl Carousel Border

### ISSUE THREAD

**Issue by ianblair44** [deepakshrma/peoplePlugin#22]
There should not be any gray border around the carousel. See the mockup. Also there shouldn't be a white space above it. 

![screen shot 2015-08-05 at 9 56 08 am](https://cloud.githubusercontent.com/assets/2794086/9091975/37fc5678-3b58-11e5-9571-61f46bad02f6.png)

**Comment by sakshityagi** [comment]
![screenshot-localhost 63342 2015-08-06 14-44-16](https://cloud.githubusercontent.com/assets/3328800/9108122/aa9a9b08-3c49-11e5-86a9-e7c4aa98323a.png)

I have removed the extra space. But there is still a thin grey line above the carousel which is due to a class on the iframe. Since iframe is a part of sdk,we cannot make changes to that.

Also, the border below and above the carousel is due to the height of the image. Lets say I have 3 images in my carousel and 2 have smaller height and one have larger height. Then carousel will have to take height of the longest image. Or else we would have to force user to upload images with same height.
